name: Pipeline CI/CD Github Actions

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  merge-and-build:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t api-valueconverter:latest .
          docker tag api-valueconverter:latest "${{ secrets.DOCKER_USERNAME }}"/api-valueconverter:latest

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/api-valueconverter:latest

      - name: <Simulation> Deploy Application
        run: echo "Work complete!"
